name: Push commit
on: push
permissions:
  contents: write

jobs:
  report:
    runs-on: windows-latest
    steps:
      - run: git config --global core.autocrlf input
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          release: false
          install: >-
            wget
            git
      - name: Create report file
        shell: msys2 {0}
        run: |
          wget -O /tmp/AllSpice-Setup-0.7.0.exe https://github.com/AllSpiceIO/AllSpice-Release/releases/download/v0.7.0/AllSpice-Setup-0.7.0.exe 
          /tmp/AllSpice-Setup-0.7.0.exe
          ls
          scripts/generate-thumbnails.sh
        
      - name: Commit report
        run: |
          git config --global user.name 'John Simons'
          git config --global user.email 'johnsel@users.noreply.github.com'
          git commit -am "Automated thumbnails"
          git push
